name: Build Firmware

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: |
          # 1. Готовим среду
          qmk setup -y
          
          # 2. Копируем файлы в официальную структуру QMK
          # Используем путь, где QMK гарантированно найдет твою клавиатуру
          mkdir -p /qmk_firmware/keyboards/handwired/macropad
          cp -r keyboards/handwired/macropad/* /qmk_firmware/keyboards/handwired/macropad/
          
          # 3. Принудительная сборка с указанием параметров
          cd /qmk_firmware
          # Запускаем сборку так, чтобы она игнорировала старые ошибки и использовала твои файлы
          qmk compile -kb handwired/macropad -km vial
