name: Build Vial Firmware

on:
  push:
    paths:
      - 'keyboards/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Tools and GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip git make rsync gcc-arm-none-eabi
          python3 -m pip install qmk
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Clone Vial-QMK
        run: |
          git clone --depth=1 https://github.com/vial-kb/vial-qmk.git
          cd vial-qmk
          git submodule update --init --recursive

      - name: Inject Keyboard Files
        run: |
          rsync -av keyboards/ vial-qmk/keyboards/

      - name: Compile Macropad Firmware
        run: |
          cd vial-qmk
          export CFLAGS="-Wno-error -Wno-return-type"
          export EXTRAFLAGS="-Wno-error -Wno-return-type"
          make handwired/macropad:vial WERROR=no

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vial-firmware
          path: vial-qmk/.build/*.uf2
