name: Build Firmware

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          submodules: recursive
          path: qmk_firmware

      - name: Checkout my keyboard
        uses: actions/checkout@v3
        with:
          path: my_keyboard

      - name: Setup & Compile
        run: |
          # 1. Показываем структуру, чтобы увидеть, где лежит макропад
          echo "--- Структура папок в qmk_firmware/keyboards/ ---"
          find qmk_firmware/keyboards/ -maxdepth 3
          
          # 2. Пересобираем среду (на всякий случай)
          python3 -m pip install --user qmk
          export PATH=$PATH:$HOME/.local/bin
          qmk setup -y
          
          # 3. Компиляция
          cd qmk_firmware
          qmk compile -kb handwired/macropad -km vial
